export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";


/*
bot ActionTypes
*/
export const BOT_GET_LIST = "BOT_GET_LIST";
export const BOT_GET_LIST_SUCCESS = "BOT_GET_LIST_SUCCESS";
export const BOT_GET_LIST_FAILURE = "BOT_GET_LIST_FAILURE";

export const BOT_CREATE = "BOT_CREATE";
export const BOT_CREATE_SUCCESS = "BOT_CREATE_SUCCESS";
export const BOT_CREATE_FAILURE = "BOT_CREATE_FAILURE";

export const BOT_DELETE = "BOT_DELETE";
export const BOT_DELETE_SUCCESS = "BOT_DELETE_SUCCESS";
export const BOT_DELETE_FAILURE = "BOT_DELETE_FAILURE";

export const BOT_UPDATE = "BOT_UPDATE";
export const BOT_UPDATE_SUCCESS = "BOT_UPDATE_SUCCESS";
export const BOT_UPDATE_FAILURE = "BOT_UPDATE_FAILURE";